"""
Background DB Log Parser
Tails the real logs generated by the genuine DB containers (MySQL, Postgres, Redis, Mongo)
and transforms them into the Dashboard SQLite format.
"""

import asyncio
import os
import re
from pathlib import Path

from .database import HoneypotDatabase

# Regex patterns for native logs
MYSQL_LOGIN = re.compile(r'(\d+-\d+-\w+:\d+:\d+\.\d+Z?)\s+\d+\s+Connect\s+([^@]+)@([\d\.]+) on')
POSTGRES_LOGIN = re.compile(r'(\d+-\d+-\d+ \d+:\d+:\d+\.\d+ \w+)\s+\[\d+\]\s+FATAL:\s+password authentication failed for user "([^"]+)"')
REDIS_LOGIN = re.compile(r'(\d+ \w+ \d+ \d+:\d+:\d+\.\d+)\s+.*Client\s+id=\d+\s+addr=([\d\.]+):\d+\s+.*user=([^ ]+)\s+.*AUTH')

class DBLogParser:
    def __init__(self, db: HoneypotDatabase):
        self.db = db
        self.log_dir = Path("/app/db-logs")
        self.running = False

    async def _tail_file(self, filepath: Path, parser_func, protocol: str):
        """Asynchronously tail a file like 'tail -f'."""
        if not filepath.exists():
            return
            
        with open(filepath, 'r') as f:
            # Seek to end on startup
            f.seek(0, 2)
            while self.running:
                line = f.readline()
                if not line:
                    await asyncio.sleep(0.5)
                    continue
                parser_func(line, protocol)

    def _parse_mysql(self, line: str, protocol: str):
        match = MYSQL_LOGIN.search(line)
        if match:
            timestamp, user, ip = match.groups()
            self.db.insert_connection(f"mysql_{hash(line)}", ip, 3306, protocol)
            self.db.insert_credential(f"mysql_{hash(line)}", protocol, ip, user, "<captured_in_pcap>")

    def _parse_postgres(self, line: str, protocol: str):
        # Postgres log lines usually begin with timestamp
        if "connection received: host=" in line:
            ip_match = re.search(r'host=([\d\.]+)', line)
            if ip_match:
                self.db.insert_connection(f"pg_{hash(line)}", ip_match.group(1), 5432, protocol)
        
        match = POSTGRES_LOGIN.search(line)
        if match:
            timestamp, user = match.groups()
            # Can't easily grab IP from just the FATAL line without state, 
            # assume unknown or parse previous line in advanced version
            self.db.insert_credential(f"pg_{hash(line)}", protocol, "unknown", user, "<failed_auth>")

    def _parse_redis(self, line: str, protocol: str):
        match = REDIS_LOGIN.search(line)
        if match:
            timestamp, ip, user = match.groups()
            self.db.insert_connection(f"redis_{hash(line)}", ip, 6379, protocol)
            self.db.insert_credential(f"redis_{hash(line)}", protocol, ip, user, "<attempt>")

    async def start(self):
        self.running = True
        
        # Paths mounted from docker-compose db-logs volume
        mysql_log = self.log_dir / "mysql" / "mysql.log"
        pg_log = self.log_dir / "postgresql" / "postgresql-*.log" # Simplified for demo, usually dynamic
        redis_log = self.log_dir / "redis" / "redis.log"
        
        # Start tail tasks for whichever files exist
        tasks = []
        if mysql_log.exists():
            tasks.append(asyncio.create_task(self._tail_file(mysql_log, self._parse_mysql, "mysql")))
        if redis_log.exists():
            tasks.append(asyncio.create_task(self._tail_file(redis_log, self._parse_redis, "redis")))
            
        if tasks:
            print(f"Started DB log parsers on {len(tasks)} target files.")
            await asyncio.gather(*tasks)

    def stop(self):
        self.running = False
